#Pull total number of orders that were completed on 18th March 2023
#Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name Doe’
#Pull total number of customers that purchased in January 2023 and the average amount spend per customer
#Pull the departments that generated less than $600 in 2022
#What is the most and least revenue we have generated by an order
#What were the orders that were purchased in our most lucrative order

#TABLE INFO :
#SALES – Date, Order_id, Item_id, Customer_id, Quantity, Revenue
#ITEMS – Item_id, Item_name, price, department
#CUSTOMERS- customer_id, first_name,last_name,Address

#Pull total number of orders that were completed on 18th March 2023
SELECT sum(s.Order_id)
FROM SALES s
JOIN CUSTOMERS c on c.customer_id = s.customer_id and c.first_name = 'John' and c. last_name = 'Doe'
WHERE s.Date = '2023-03-18'

#Pull total number of customers that purchased in January 2023 and the average amount spend per customer
WITH Jan_Customer as (
    SELECT customer_id
    FROM CUSTOMERS c.customer_id
    JOIN SALES on s.customer_id = c.customer_id and s.Date > '2022-12-31' and s.Date < '2023-02-01'

    )

SELECT COUNT(DISTINCT s.customer_id) AS total_customers, AVG(s.revenue) AS avg_spend_per_customer
FROM SALES s
JOIN Jan_Customer jc on jc.customer_id s.customer_id

#Pull the departments that generated less than $600 in 2022
SELECT i.department, sum(s.Revenue) 
FROM ITEMS i
JOIN SALES s on s.Item_id = i.Item_id
GROUP BY 1
HAVING sum(s.Revenue) < 600

#What is the most and least revenue we have generated by an order
SELECT MAX(revenue) AS max_order_revenue, MIN(revenue) AS min_order_revenue
FROM SALES

#What were the orders that were purchased in our most lucrative order
SELECT  order_id, MAX(revenue) AS max_revenue
FROM SALES
GROUP BY order_id
ORDER BY max_revenue DESC
LIMIT 1
